name: penny_planner
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI and Navigation Packages
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  curved_navigation_bar: ^1.0.3
  google_fonts: ^6.2.1  # Custom fonts for a modern UI
  flutter_switch: ^0.3.2  # Improved switch UI

  # Animation and 3D
  rive: ^0.13.3  # 3D animations
  lottie: ^3.3.1  # Updated to latest version for JSON-based animations

  # Firebase Dependencies
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/  # Folder for multiple animations
    - assets/animations/setup_intro.json  # Explicitly list animation for Setup Page 1
    - assets/animations/Piggy Bank.json  # Explicitly list Piggy Bank animation for Setup Page 2
    - assets/images/ppPinkLogo.png
    - assets/images/ppWhiteLogo.png  # Added new logo

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700